### ISSUE TITLE
is rust dependency: `proxy_canister_types` on crate public repositories  yet ?

### ISSUE THREAD

**Issue by q2333gh** [omnia-network/ic-http-proxy#1]
currently in this example code of cargo.toml use :
proxy_canister_types = { path = "../../../../../src/proxy_canister_types" }
which is not easy to use in other project as a lib

**Comment by q2333gh** [comment]
in cargo.toml use : 
`proxy_canister_types = { path = "../../../../../src/proxy_canister_types" }`
which is not easy to use in other project as a lib

**Comment by ilbertt** [comment]
For now, the `proxy_canister_types` package is still not released as a public crate. However, to import it in your project, you can add this line in your _Cargo.toml_ file:
```toml
proxy_canister_types = { git = "https://github.com/omnia-network/ic-http-proxy", package = "proxy_canister_types" }
```

I'll update the example's README also. If it works for you, please close the issue.

**Comment by q2333gh** [comment]
the import method you mentioned works ok. thanks !
